package utils

import (
	"errors"
	"regexp"
	"strings"
)

// The Elestio API client sends the session JWT as a `jwt` query parameter.
// net/http embeds the full request URL in the errors it returns (*url.Error),
// so a network failure or timeout would otherwise print the token in
// Terraform diagnostics and CI logs.
var secretPatterns = []struct {
	re   *regexp.Regexp
	repl string
}{
	{regexp.MustCompile(`(?i)([?&]jwt=)[^&\s"']*`), `${1}REDACTED`},
	{regexp.MustCompile(`(?i)("jwt"\s*:\s*")[^"]*(")`), `${1}REDACTED${2}`},
	{regexp.MustCompile(`(?i)(bearer\s+)[A-Za-z0-9._~+/=-]+`), `${1}REDACTED`},
}

// RedactSecrets removes API session tokens from s.
func RedactSecrets(s string) string {
	for _, p := range secretPatterns {
		s = p.re.ReplaceAllString(s, p.repl)
	}
	return s
}

// RedactError returns the message of err with secrets removed.
// It returns an empty string for a nil error.
func RedactError(err error) string {
	if err == nil {
		return ""
	}
	return RedactSecrets(err.Error())
}

// Messages generated by the Elestio API client itself when a lookup succeeds at
// the HTTP level but returns no object.
var notFoundMessages = map[string]struct{}{
	"service not found":       {},
	"project not found":       {},
	"load balancer not found": {},
}

// The backend answers HTTP 401 (not 404) when a service or load balancer does
// not exist or is being deleted. Only these codes prove that; other 401 codes
// such as Unauthorized (expired or invalid token), InvalidPermission or
// MissingPermission are real failures and must never be read as "deleted".
var goneCodePattern = regexp.MustCompile(`"code"\s*:\s*"(InvalidServer|service_deleted)"`)

const status401Prefix = "request failed with status code 401"

// IsNotFound reports whether err means the remote object does not exist (or is
// already deleted), as opposed to a transport, authentication or server
// failure. The client does not expose typed errors, so this matches its exact
// "not found" messages and the backend's 401 codes for a missing server.
func IsNotFound(err error) bool {
	if err == nil {
		return false
	}
	for e := err; e != nil; e = errors.Unwrap(e) {
		msg := e.Error()
		if _, ok := notFoundMessages[msg]; ok {
			return true
		}
		if strings.HasPrefix(msg, status401Prefix) && goneCodePattern.MatchString(msg) {
			return true
		}
	}
	return false
}
